// Code generated by MockGen. DO NOT EDIT.
// Source: D:/TBank/sem2/TGBot/go-MAtveyka12/internal/scrapper/application/scheduler/scheduler.go
//
// Generated by this command:
//
//	mockgen -source=D:/TBank/sem2/TGBot/go-MAtveyka12/internal/scrapper/application/scheduler/scheduler.go -destination=D:/TBank/sem2/TGBot/go-MAtveyka12/internal/scrapper/application/scheduler/mock/scheduler.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	clients "github.com/es-debug/backend-academy-2024-go-template/internal/scrapper/infrastructure/client"
	gomock "go.uber.org/mock/gomock"
)

// MockScheduler is a mock of Scheduler interface.
type MockScheduler struct {
	ctrl     *gomock.Controller
	recorder *MockSchedulerMockRecorder
	isgomock struct{}
}

// MockSchedulerMockRecorder is the mock recorder for MockScheduler.
type MockSchedulerMockRecorder struct {
	mock *MockScheduler
}

// NewMockScheduler creates a new mock instance.
func NewMockScheduler(ctrl *gomock.Controller) *MockScheduler {
	mock := &MockScheduler{ctrl: ctrl}
	mock.recorder = &MockSchedulerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScheduler) EXPECT() *MockSchedulerMockRecorder {
	return m.recorder
}

// AddLink mocks base method.
func (m *MockScheduler) AddLink(link string, userID, linkID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddLink", link, userID, linkID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddLink indicates an expected call of AddLink.
func (mr *MockSchedulerMockRecorder) AddLink(link, userID, linkID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddLink", reflect.TypeOf((*MockScheduler)(nil).AddLink), link, userID, linkID)
}

// HandleCommits mocks base method.
func (m *MockScheduler) HandleCommits(ctx context.Context, ghClient clients.Client, owner, repo, link string, userID, linkID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleCommits", ctx, ghClient, owner, repo, link, userID, linkID)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandleCommits indicates an expected call of HandleCommits.
func (mr *MockSchedulerMockRecorder) HandleCommits(ctx, ghClient, owner, repo, link, userID, linkID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleCommits", reflect.TypeOf((*MockScheduler)(nil).HandleCommits), ctx, ghClient, owner, repo, link, userID, linkID)
}

// HandlePullRequests mocks base method.
func (m *MockScheduler) HandlePullRequests(ctx context.Context, ghClient clients.Client, owner, repo, link string, userID, linkID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandlePullRequests", ctx, ghClient, owner, repo, link, userID, linkID)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandlePullRequests indicates an expected call of HandlePullRequests.
func (mr *MockSchedulerMockRecorder) HandlePullRequests(ctx, ghClient, owner, repo, link, userID, linkID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandlePullRequests", reflect.TypeOf((*MockScheduler)(nil).HandlePullRequests), ctx, ghClient, owner, repo, link, userID, linkID)
}

// MonitorRepo mocks base method.
func (m *MockScheduler) MonitorRepo(ctx context.Context, owner, repo, link string, userID, linkID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MonitorRepo", ctx, owner, repo, link, userID, linkID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MonitorRepo indicates an expected call of MonitorRepo.
func (mr *MockSchedulerMockRecorder) MonitorRepo(ctx, owner, repo, link, userID, linkID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MonitorRepo", reflect.TypeOf((*MockScheduler)(nil).MonitorRepo), ctx, owner, repo, link, userID, linkID)
}

// MonitorStackOverflow mocks base method.
func (m *MockScheduler) MonitorStackOverflow(ctx context.Context, questionID int, question, link string, userID, linkID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MonitorStackOverflow", ctx, questionID, question, link, userID, linkID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MonitorStackOverflow indicates an expected call of MonitorStackOverflow.
func (mr *MockSchedulerMockRecorder) MonitorStackOverflow(ctx, questionID, question, link, userID, linkID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MonitorStackOverflow", reflect.TypeOf((*MockScheduler)(nil).MonitorStackOverflow), ctx, questionID, question, link, userID, linkID)
}

// RemoveLink mocks base method.
func (m *MockScheduler) RemoveLink(link string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveLink", link)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveLink indicates an expected call of RemoveLink.
func (mr *MockSchedulerMockRecorder) RemoveLink(link any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveLink", reflect.TypeOf((*MockScheduler)(nil).RemoveLink), link)
}

// Stop mocks base method.
func (m *MockScheduler) Stop() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop")
	ret0, _ := ret[0].(error)
	return ret0
}

// Stop indicates an expected call of Stop.
func (mr *MockSchedulerMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockScheduler)(nil).Stop))
}
