FROM golang:1.24 AS builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY config/config.yaml ./config/config.yaml
COPY .env ./

COPY . .

RUN go build -o scrapper cmd/scrapper/main.go

FROM debian:bookworm-slim

WORKDIR /root/

RUN apt-get update && apt-get install -y ca-certificates && update-ca-certificates

COPY --from=builder /app/scrapper .
COPY --from=builder /app/config/config.yaml ./config/config.yaml
COPY --from=builder /app/.env ./

CMD ["./scrapper"]
