FROM golang:1.24 AS builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY config/config.yaml ./config/config.yaml
COPY .env ./

COPY . .

RUN go build -o bot cmd/bot/main.go

FROM debian:bookworm-slim

WORKDIR /root/

RUN apt-get update && \
    apt-get install -y ca-certificates && \
    update-ca-certificates && \
    rm -rf /var/lib/apt/lists/*

COPY --from=builder /app/bot .
COPY --from=builder /app/config/config.yaml ./config/config.yaml
COPY --from=builder /app/.env ./
COPY --from=builder /app/patterns/patterns.yaml ./patterns/patterns.yaml
COPY --from=builder /app/templates/user_details.tmpl ./templates/user_details.tmpl
COPY --from=builder /app/templates/help.tmpl ./templates/help.tmpl

CMD ["./bot"]