// Code generated by MockGen. DO NOT EDIT.
// Source: D:\TBank\sem2\TGBot\go-MAtveyka12\internal\scrapper\infrastructure\producer\producer.go
//
// Generated by this command:
//
//	mockgen -source=D:\TBank\sem2\TGBot\go-MAtveyka12\internal\scrapper\infrastructure\producer\producer.go -destination=D:\TBank\sem2\TGBot\go-MAtveyka12\internal\scrapper\infrastructure\producer\mock\producer.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	producer "github.com/es-debug/backend-academy-2024-go-template/internal/scrapper/domain/producer"
	gomock "go.uber.org/mock/gomock"
)

// MockProdKafkaOrHTTP is a mock of ProdKafkaOrHTTP interface.
type MockProdKafkaOrHTTP struct {
	ctrl     *gomock.Controller
	recorder *MockProdKafkaOrHTTPMockRecorder
	isgomock struct{}
}

// MockProdKafkaOrHTTPMockRecorder is the mock recorder for MockProdKafkaOrHTTP.
type MockProdKafkaOrHTTPMockRecorder struct {
	mock *MockProdKafkaOrHTTP
}

// NewMockProdKafkaOrHTTP creates a new mock instance.
func NewMockProdKafkaOrHTTP(ctrl *gomock.Controller) *MockProdKafkaOrHTTP {
	mock := &MockProdKafkaOrHTTP{ctrl: ctrl}
	mock.recorder = &MockProdKafkaOrHTTPMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProdKafkaOrHTTP) EXPECT() *MockProdKafkaOrHTTPMockRecorder {
	return m.recorder
}

// Run mocks base method.
func (m *MockProdKafkaOrHTTP) Run() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Run")
}

// Run indicates an expected call of Run.
func (mr *MockProdKafkaOrHTTPMockRecorder) Run() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockProdKafkaOrHTTP)(nil).Run))
}

// SendUpdate mocks base method.
func (m *MockProdKafkaOrHTTP) SendUpdate(update producer.LinkUpdate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendUpdate", update)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendUpdate indicates an expected call of SendUpdate.
func (mr *MockProdKafkaOrHTTPMockRecorder) SendUpdate(update any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendUpdate", reflect.TypeOf((*MockProdKafkaOrHTTP)(nil).SendUpdate), update)
}

// SendUpdatePR mocks base method.
func (m *MockProdKafkaOrHTTP) SendUpdatePR(update producer.LinkUpdate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendUpdatePR", update)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendUpdatePR indicates an expected call of SendUpdatePR.
func (mr *MockProdKafkaOrHTTPMockRecorder) SendUpdatePR(update any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendUpdatePR", reflect.TypeOf((*MockProdKafkaOrHTTP)(nil).SendUpdatePR), update)
}

// Stop mocks base method.
func (m *MockProdKafkaOrHTTP) Stop() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Stop")
}

// Stop indicates an expected call of Stop.
func (mr *MockProdKafkaOrHTTPMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockProdKafkaOrHTTP)(nil).Stop))
}
