// Code generated by MockGen. DO NOT EDIT.
// Source: D:\TBank\sem2\TGBot\go-MAtveyka12\internal\scrapper\infrastructure\client\client.go
//
// Generated by this command:
//
//	mockgen -source=D:\TBank\sem2\TGBot\go-MAtveyka12\internal\scrapper\infrastructure\client\client.go -destination=D:\TBank\sem2\TGBot\go-MAtveyka12\internal\scrapper\infrastructure\client\mock\client.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	github "github.com/es-debug/backend-academy-2024-go-template/internal/scrapper/domain/github"
	stackoverflow "github.com/es-debug/backend-academy-2024-go-template/internal/scrapper/domain/stackoverflow"
	clients "github.com/es-debug/backend-academy-2024-go-template/internal/scrapper/infrastructure/client"
	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// GetLatestAnswers mocks base method.
func (m *MockClient) GetLatestAnswers(ctx context.Context, questionID int) ([]stackoverflow.Answer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestAnswers", ctx, questionID)
	ret0, _ := ret[0].([]stackoverflow.Answer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestAnswers indicates an expected call of GetLatestAnswers.
func (mr *MockClientMockRecorder) GetLatestAnswers(ctx, questionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestAnswers", reflect.TypeOf((*MockClient)(nil).GetLatestAnswers), ctx, questionID)
}

// GetLatestComments mocks base method.
func (m *MockClient) GetLatestComments(ctx context.Context, questionID int) ([]stackoverflow.Comment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestComments", ctx, questionID)
	ret0, _ := ret[0].([]stackoverflow.Comment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestComments indicates an expected call of GetLatestComments.
func (mr *MockClientMockRecorder) GetLatestComments(ctx, questionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestComments", reflect.TypeOf((*MockClient)(nil).GetLatestComments), ctx, questionID)
}

// GetLatestCommits mocks base method.
func (m *MockClient) GetLatestCommits(ctx context.Context, owner, repo string) ([]github.Commit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestCommits", ctx, owner, repo)
	ret0, _ := ret[0].([]github.Commit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestCommits indicates an expected call of GetLatestCommits.
func (mr *MockClientMockRecorder) GetLatestCommits(ctx, owner, repo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestCommits", reflect.TypeOf((*MockClient)(nil).GetLatestCommits), ctx, owner, repo)
}

// GetLatestPRs mocks base method.
func (m *MockClient) GetLatestPRs(ctx context.Context, owner, repo string) ([]github.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestPRs", ctx, owner, repo)
	ret0, _ := ret[0].([]github.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestPRs indicates an expected call of GetLatestPRs.
func (mr *MockClientMockRecorder) GetLatestPRs(ctx, owner, repo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestPRs", reflect.TypeOf((*MockClient)(nil).GetLatestPRs), ctx, owner, repo)
}

// GetType mocks base method.
func (m *MockClient) GetType() clients.ClientType {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetType")
	ret0, _ := ret[0].(clients.ClientType)
	return ret0
}

// GetType indicates an expected call of GetType.
func (mr *MockClientMockRecorder) GetType() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetType", reflect.TypeOf((*MockClient)(nil).GetType))
}
