// Code generated by MockGen. DO NOT EDIT.
// Source: D:\TBank\sem2\TGBot\go-MAtveyka12\internal\bot\infrastructure\scrapper\scrapper.go
//
// Generated by this command:
//
//	mockgen -source=D:\TBank\sem2\TGBot\go-MAtveyka12\internal\bot\infrastructure\scrapper\scrapper.go -destination=D:\TBank\sem2\TGBot\go-MAtveyka12\internal\bot\infrastructure\scrapper\mock\scrapper.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	domain "github.com/es-debug/backend-academy-2024-go-template/internal/bot/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockScraperClient is a mock of ScraperClient interface.
type MockScraperClient struct {
	ctrl     *gomock.Controller
	recorder *MockScraperClientMockRecorder
	isgomock struct{}
}

// MockScraperClientMockRecorder is the mock recorder for MockScraperClient.
type MockScraperClientMockRecorder struct {
	mock *MockScraperClient
}

// NewMockScraperClient creates a new mock instance.
func NewMockScraperClient(ctrl *gomock.Controller) *MockScraperClient {
	mock := &MockScraperClient{ctrl: ctrl}
	mock.recorder = &MockScraperClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScraperClient) EXPECT() *MockScraperClientMockRecorder {
	return m.recorder
}

// AddLink mocks base method.
func (m *MockScraperClient) AddLink(ctx context.Context, link domain.Link) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddLink", ctx, link)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddLink indicates an expected call of AddLink.
func (mr *MockScraperClientMockRecorder) AddLink(ctx, link any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddLink", reflect.TypeOf((*MockScraperClient)(nil).AddLink), ctx, link)
}

// GetLinks mocks base method.
func (m *MockScraperClient) GetLinks(ctx context.Context, userID int64) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLinks", ctx, userID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLinks indicates an expected call of GetLinks.
func (mr *MockScraperClientMockRecorder) GetLinks(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLinks", reflect.TypeOf((*MockScraperClient)(nil).GetLinks), ctx, userID)
}

// RegisterUser mocks base method.
func (m *MockScraperClient) RegisterUser(ctx context.Context, user domain.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterUser", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterUser indicates an expected call of RegisterUser.
func (mr *MockScraperClientMockRecorder) RegisterUser(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterUser", reflect.TypeOf((*MockScraperClient)(nil).RegisterUser), ctx, user)
}

// RemoveLink mocks base method.
func (m *MockScraperClient) RemoveLink(ctx context.Context, link string, userID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveLink", ctx, link, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveLink indicates an expected call of RemoveLink.
func (mr *MockScraperClientMockRecorder) RemoveLink(ctx, link, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveLink", reflect.TypeOf((*MockScraperClient)(nil).RemoveLink), ctx, link, userID)
}
