// Code generated by MockGen. DO NOT EDIT.
// Source: D:\TBank\sem2\TGBot\go-MAtveyka12\internal\scrapper\application\service\service.go
//
// Generated by this command:
//
//	mockgen -source=D:\TBank\sem2\TGBot\go-MAtveyka12\internal\scrapper\application\service\service.go -destination=D:\TBank\sem2\TGBot\go-MAtveyka12\internal\scrapper\application\service\mock\service.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// AddLink mocks base method.
func (m *MockService) AddLink(ctx context.Context, userID int, link string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddLink", ctx, userID, link)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddLink indicates an expected call of AddLink.
func (mr *MockServiceMockRecorder) AddLink(ctx, userID, link any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddLink", reflect.TypeOf((*MockService)(nil).AddLink), ctx, userID, link)
}

// DeleteChat mocks base method.
func (m *MockService) DeleteChat(ctx context.Context, userID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteChat", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteChat indicates an expected call of DeleteChat.
func (mr *MockServiceMockRecorder) DeleteChat(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteChat", reflect.TypeOf((*MockService)(nil).DeleteChat), ctx, userID)
}

// DeleteLink mocks base method.
func (m *MockService) DeleteLink(ctx context.Context, userID, linkID int, link string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteLink", ctx, userID, linkID, link)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteLink indicates an expected call of DeleteLink.
func (mr *MockServiceMockRecorder) DeleteLink(ctx, userID, linkID, link any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteLink", reflect.TypeOf((*MockService)(nil).DeleteLink), ctx, userID, linkID, link)
}

// GetAllLinks mocks base method.
func (m *MockService) GetAllLinks(ctx context.Context, userID int) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllLinks", ctx, userID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllLinks indicates an expected call of GetAllLinks.
func (mr *MockServiceMockRecorder) GetAllLinks(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllLinks", reflect.TypeOf((*MockService)(nil).GetAllLinks), ctx, userID)
}

// RegisterChat mocks base method.
func (m *MockService) RegisterChat(ctx context.Context, userID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterChat", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterChat indicates an expected call of RegisterChat.
func (mr *MockServiceMockRecorder) RegisterChat(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterChat", reflect.TypeOf((*MockService)(nil).RegisterChat), ctx, userID)
}
