// Code generated by MockGen. DO NOT EDIT.
// Source: D:\TBank\sem2\TGBot\go-MAtveyka12\internal\bot\infrastructure\storage\repository.go
//
// Generated by this command:
//
//	mockgen -source=D:\TBank\sem2\TGBot\go-MAtveyka12\internal\bot\infrastructure\storage\repository.go -destination=D:\TBank\sem2\TGBot\go-MAtveyka12\internal\bot\infrastructure\storage\mock_repository.go -package=storage
//

// Package storage is a generated GoMock package.
package storage

import (
	reflect "reflect"

	domain "github.com/es-debug/backend-academy-2024-go-template/internal/bot/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockRepo is a mock of Repo interface.
type MockRepo struct {
	ctrl     *gomock.Controller
	recorder *MockRepoMockRecorder
	isgomock struct{}
}

// MockRepoMockRecorder is the mock recorder for MockRepo.
type MockRepoMockRecorder struct {
	mock *MockRepo
}

// NewMockRepo creates a new mock instance.
func NewMockRepo(ctrl *gomock.Controller) *MockRepo {
	mock := &MockRepo{ctrl: ctrl}
	mock.recorder = &MockRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepo) EXPECT() *MockRepoMockRecorder {
	return m.recorder
}

// AddLink mocks base method.
func (m *MockRepo) AddLink(link domain.Link) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddLink", link)
}

// AddLink indicates an expected call of AddLink.
func (mr *MockRepoMockRecorder) AddLink(link any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddLink", reflect.TypeOf((*MockRepo)(nil).AddLink), link)
}

// DeleteLink mocks base method.
func (m *MockRepo) DeleteLink(url string, userID int64) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteLink", url, userID)
	ret0, _ := ret[0].(bool)
	return ret0
}

// DeleteLink indicates an expected call of DeleteLink.
func (mr *MockRepoMockRecorder) DeleteLink(url, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteLink", reflect.TypeOf((*MockRepo)(nil).DeleteLink), url, userID)
}

// GetLinks mocks base method.
func (m *MockRepo) GetLinks(userID int64) []domain.Link {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLinks", userID)
	ret0, _ := ret[0].([]domain.Link)
	return ret0
}

// GetLinks indicates an expected call of GetLinks.
func (mr *MockRepoMockRecorder) GetLinks(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLinks", reflect.TypeOf((*MockRepo)(nil).GetLinks), userID)
}
