// Code generated by MockGen. DO NOT EDIT.
// Source: D:\TBank\sem2\TGBot\go-MAtveyka12\internal\scrapper\infrastructure\repository\link_repository.go
//
// Generated by this command:
//
//	mockgen -source=D:\TBank\sem2\TGBot\go-MAtveyka12\internal\scrapper\infrastructure\repository\link_repository.go -destination=D:\TBank\sem2\TGBot\go-MAtveyka12\internal\scrapper\infrastructure\repository\mock\link_repository.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockLinkRepository is a mock of LinkRepository interface.
type MockLinkRepository struct {
	ctrl     *gomock.Controller
	recorder *MockLinkRepositoryMockRecorder
	isgomock struct{}
}

// MockLinkRepositoryMockRecorder is the mock recorder for MockLinkRepository.
type MockLinkRepositoryMockRecorder struct {
	mock *MockLinkRepository
}

// NewMockLinkRepository creates a new mock instance.
func NewMockLinkRepository(ctrl *gomock.Controller) *MockLinkRepository {
	mock := &MockLinkRepository{ctrl: ctrl}
	mock.recorder = &MockLinkRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLinkRepository) EXPECT() *MockLinkRepositoryMockRecorder {
	return m.recorder
}

// AddLink mocks base method.
func (m *MockLinkRepository) AddLink(ctx context.Context, userID int, link string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddLink", ctx, userID, link)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddLink indicates an expected call of AddLink.
func (mr *MockLinkRepositoryMockRecorder) AddLink(ctx, userID, link any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddLink", reflect.TypeOf((*MockLinkRepository)(nil).AddLink), ctx, userID, link)
}

// DeleteAllLinks mocks base method.
func (m *MockLinkRepository) DeleteAllLinks(ctx context.Context, userID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAllLinks", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAllLinks indicates an expected call of DeleteAllLinks.
func (mr *MockLinkRepositoryMockRecorder) DeleteAllLinks(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAllLinks", reflect.TypeOf((*MockLinkRepository)(nil).DeleteAllLinks), ctx, userID)
}

// DeleteLink mocks base method.
func (m *MockLinkRepository) DeleteLink(ctx context.Context, userID, linkID int, link string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteLink", ctx, userID, linkID, link)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteLink indicates an expected call of DeleteLink.
func (mr *MockLinkRepositoryMockRecorder) DeleteLink(ctx, userID, linkID, link any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteLink", reflect.TypeOf((*MockLinkRepository)(nil).DeleteLink), ctx, userID, linkID, link)
}

// GetAllLinks mocks base method.
func (m *MockLinkRepository) GetAllLinks(ctx context.Context, userID int) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllLinks", ctx, userID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllLinks indicates an expected call of GetAllLinks.
func (mr *MockLinkRepositoryMockRecorder) GetAllLinks(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllLinks", reflect.TypeOf((*MockLinkRepository)(nil).GetAllLinks), ctx, userID)
}

// GetLink mocks base method.
func (m *MockLinkRepository) GetLink(ctx context.Context, userID, linkID int) (string, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLink", ctx, userID, linkID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetLink indicates an expected call of GetLink.
func (mr *MockLinkRepositoryMockRecorder) GetLink(ctx, userID, linkID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLink", reflect.TypeOf((*MockLinkRepository)(nil).GetLink), ctx, userID, linkID)
}

// GetLinkIDByURL mocks base method.
func (m *MockLinkRepository) GetLinkIDByURL(ctx context.Context, userID int, url string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLinkIDByURL", ctx, userID, url)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLinkIDByURL indicates an expected call of GetLinkIDByURL.
func (mr *MockLinkRepositoryMockRecorder) GetLinkIDByURL(ctx, userID, url any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLinkIDByURL", reflect.TypeOf((*MockLinkRepository)(nil).GetLinkIDByURL), ctx, userID, url)
}
