// Code generated by MockGen. DO NOT EDIT.
// Source: D:\TBank\sem2\TGBot\go-MAtveyka12\internal\scrapper\infrastructure\repository\repository.go
//
// Generated by this command:
//
//	mockgen -source=D:\TBank\sem2\TGBot\go-MAtveyka12\internal\scrapper\infrastructure\repository\repository.go -destination=D:\TBank\sem2\TGBot\go-MAtveyka12\internal\scrapper\infrastructure\repository\mock\repository.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// AddLink mocks base method.
func (m *MockRepository) AddLink(ctx context.Context, userID int, link string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddLink", ctx, userID, link)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddLink indicates an expected call of AddLink.
func (mr *MockRepositoryMockRecorder) AddLink(ctx, userID, link any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddLink", reflect.TypeOf((*MockRepository)(nil).AddLink), ctx, userID, link)
}

// ChatExists mocks base method.
func (m *MockRepository) ChatExists(ctx context.Context, userID int) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChatExists", ctx, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ChatExists indicates an expected call of ChatExists.
func (mr *MockRepositoryMockRecorder) ChatExists(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChatExists", reflect.TypeOf((*MockRepository)(nil).ChatExists), ctx, userID)
}

// DeleteAllLinks mocks base method.
func (m *MockRepository) DeleteAllLinks(ctx context.Context, userID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAllLinks", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAllLinks indicates an expected call of DeleteAllLinks.
func (mr *MockRepositoryMockRecorder) DeleteAllLinks(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAllLinks", reflect.TypeOf((*MockRepository)(nil).DeleteAllLinks), ctx, userID)
}

// DeleteChat mocks base method.
func (m *MockRepository) DeleteChat(ctx context.Context, userID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteChat", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteChat indicates an expected call of DeleteChat.
func (mr *MockRepositoryMockRecorder) DeleteChat(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteChat", reflect.TypeOf((*MockRepository)(nil).DeleteChat), ctx, userID)
}

// DeleteLink mocks base method.
func (m *MockRepository) DeleteLink(ctx context.Context, userID, linkID int, link string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteLink", ctx, userID, linkID, link)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteLink indicates an expected call of DeleteLink.
func (mr *MockRepositoryMockRecorder) DeleteLink(ctx, userID, linkID, link any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteLink", reflect.TypeOf((*MockRepository)(nil).DeleteLink), ctx, userID, linkID, link)
}

// GetAllLinks mocks base method.
func (m *MockRepository) GetAllLinks(ctx context.Context, userID int) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllLinks", ctx, userID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllLinks indicates an expected call of GetAllLinks.
func (mr *MockRepositoryMockRecorder) GetAllLinks(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllLinks", reflect.TypeOf((*MockRepository)(nil).GetAllLinks), ctx, userID)
}

// GetLink mocks base method.
func (m *MockRepository) GetLink(ctx context.Context, userID, linkID int) (string, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLink", ctx, userID, linkID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetLink indicates an expected call of GetLink.
func (mr *MockRepositoryMockRecorder) GetLink(ctx, userID, linkID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLink", reflect.TypeOf((*MockRepository)(nil).GetLink), ctx, userID, linkID)
}

// GetLinkIDByURL mocks base method.
func (m *MockRepository) GetLinkIDByURL(ctx context.Context, userID int, url string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLinkIDByURL", ctx, userID, url)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLinkIDByURL indicates an expected call of GetLinkIDByURL.
func (mr *MockRepositoryMockRecorder) GetLinkIDByURL(ctx, userID, url any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLinkIDByURL", reflect.TypeOf((*MockRepository)(nil).GetLinkIDByURL), ctx, userID, url)
}

// RegisterChat mocks base method.
func (m *MockRepository) RegisterChat(ctx context.Context, userID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterChat", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterChat indicates an expected call of RegisterChat.
func (mr *MockRepositoryMockRecorder) RegisterChat(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterChat", reflect.TypeOf((*MockRepository)(nil).RegisterChat), ctx, userID)
}
