// Code generated by MockGen. DO NOT EDIT.
// Source: D:/TBank/sem2/TGBot/go-MAtveyka12/internal/scrapper/infrastructure/repository/tx_manager.go
//
// Generated by this command:
//
//	mockgen -source=D:/TBank/sem2/TGBot/go-MAtveyka12/internal/scrapper/infrastructure/repository/tx_manager.go -destination=D:/TBank/sem2/TGBot/go-MAtveyka12/internal/scrapper/infrastructure/repository/mock/tx_manager.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	repository "github.com/es-debug/backend-academy-2024-go-template/internal/scrapper/infrastructure/repository"
	gomock "go.uber.org/mock/gomock"
)

// MockTxManager is a mock of TxManager interface.
type MockTxManager struct {
	ctrl     *gomock.Controller
	recorder *MockTxManagerMockRecorder
	isgomock struct{}
}

// MockTxManagerMockRecorder is the mock recorder for MockTxManager.
type MockTxManagerMockRecorder struct {
	mock *MockTxManager
}

// NewMockTxManager creates a new mock instance.
func NewMockTxManager(ctrl *gomock.Controller) *MockTxManager {
	mock := &MockTxManager{ctrl: ctrl}
	mock.recorder = &MockTxManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTxManager) EXPECT() *MockTxManagerMockRecorder {
	return m.recorder
}

// Do mocks base method.
func (m *MockTxManager) Do(arg0 context.Context, arg1 func(context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Do", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Do indicates an expected call of Do.
func (mr *MockTxManagerMockRecorder) Do(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockTxManager)(nil).Do), arg0, arg1)
}

// MockTransaction is a mock of Transaction interface.
type MockTransaction struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionMockRecorder
	isgomock struct{}
}

// MockTransactionMockRecorder is the mock recorder for MockTransaction.
type MockTransactionMockRecorder struct {
	mock *MockTransaction
}

// NewMockTransaction creates a new mock instance.
func NewMockTransaction(ctrl *gomock.Controller) *MockTransaction {
	mock := &MockTransaction{ctrl: ctrl}
	mock.recorder = &MockTransactionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransaction) EXPECT() *MockTransactionMockRecorder {
	return m.recorder
}

// Begin mocks base method.
func (m *MockTransaction) Begin() any {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Begin")
	ret0, _ := ret[0].(any)
	return ret0
}

// Begin indicates an expected call of Begin.
func (mr *MockTransactionMockRecorder) Begin() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Begin", reflect.TypeOf((*MockTransaction)(nil).Begin))
}

// Commit mocks base method.
func (m *MockTransaction) Commit(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Commit", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Commit indicates an expected call of Commit.
func (mr *MockTransactionMockRecorder) Commit(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Commit", reflect.TypeOf((*MockTransaction)(nil).Commit), arg0)
}

// Rollback mocks base method.
func (m *MockTransaction) Rollback(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rollback", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Rollback indicates an expected call of Rollback.
func (mr *MockTransactionMockRecorder) Rollback(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rollback", reflect.TypeOf((*MockTransaction)(nil).Rollback), arg0)
}

// MockCtxManager is a mock of CtxManager interface.
type MockCtxManager struct {
	ctrl     *gomock.Controller
	recorder *MockCtxManagerMockRecorder
	isgomock struct{}
}

// MockCtxManagerMockRecorder is the mock recorder for MockCtxManager.
type MockCtxManagerMockRecorder struct {
	mock *MockCtxManager
}

// NewMockCtxManager creates a new mock instance.
func NewMockCtxManager(ctrl *gomock.Controller) *MockCtxManager {
	mock := &MockCtxManager{ctrl: ctrl}
	mock.recorder = &MockCtxManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCtxManager) EXPECT() *MockCtxManagerMockRecorder {
	return m.recorder
}

// ByKey mocks base method.
func (m *MockCtxManager) ByKey(arg0 context.Context, arg1 repository.CtxKey) repository.Transaction {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ByKey", arg0, arg1)
	ret0, _ := ret[0].(repository.Transaction)
	return ret0
}

// ByKey indicates an expected call of ByKey.
func (mr *MockCtxManagerMockRecorder) ByKey(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ByKey", reflect.TypeOf((*MockCtxManager)(nil).ByKey), arg0, arg1)
}

// CtxKey mocks base method.
func (m *MockCtxManager) CtxKey() repository.CtxKey {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CtxKey")
	ret0, _ := ret[0].(repository.CtxKey)
	return ret0
}

// CtxKey indicates an expected call of CtxKey.
func (mr *MockCtxManagerMockRecorder) CtxKey() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CtxKey", reflect.TypeOf((*MockCtxManager)(nil).CtxKey))
}

// Default mocks base method.
func (m *MockCtxManager) Default(arg0 context.Context) repository.Transaction {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Default", arg0)
	ret0, _ := ret[0].(repository.Transaction)
	return ret0
}

// Default indicates an expected call of Default.
func (mr *MockCtxManagerMockRecorder) Default(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Default", reflect.TypeOf((*MockCtxManager)(nil).Default), arg0)
}
